services:
    postgres:
        container_name: messenger-postgres
        image: postgres:18-bookworm
        restart: unless-stopped

        user: "1000:1000"

        ports:
            - "5432:5432"

        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: test

        volumes:
            - messenger-postgres-data:/var/lib/postgresql

volumes:
    messenger-postgres-data:
